name: Trigger workflow 
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Trigger workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: deepakdinesh1123
          repo: actions
          github_token: ${{  secrets.ACCESS_TOKEN }}
          workflow_file_name: airspeed.yml
