name: Docker

on: [push]

jobs:
    
  run-django:
    runs-on: self-hosted
    steps:
      - name: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: checkout
        uses: actions/checkout@v3
      - name: install django
        run: pip install django gunicorn
      - name: create django project
        run: django-admin startproject polls
      - name: run server
        run: cd polls && gunicorn polls.wsgi --daemon
  
  run-locust:
    runs-on: self-hosted
    needs: run-django
    steps:
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: install locust
        run: pip install locust
      - name: checkout 
        uses: actions/checkout@v3
      - name: run locust
        run: locust --headless --users 10 --spawn-rate 1 -H http://localhost:8000/ --csv=result -t1m
        

