name: Docker

on: [push]

jobs:
    
  run-django:
    runs-on: ubuntu-latest
    steps:
      - name: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: checkout
        uses: actions/checkout@v3
      - name: install django
        run: pip install django 
      - name: create django project
        run: django-admin startproject test && cd test
      - name: run server
        run: python manage.py runserver
      - name: run python file
        run: pyton some.py
        

