name: Benchmark

on:
  pull_request:
    types: [ labeled ]

jobs:
  Run_benchmarks:
    if: ${{ github.event.label.name == 'benchmark'}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout benchmarks
        uses: actions/checkout@v3
        with:
          repository: smithdc1/django-asv
          path: "."
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Cache Django
        uses: actions/cache@v3
        with:
          path: Django/*
          key: Django
      - name: Run Benchmarks
        shell: bash -l {0}
        run: |-
          asv machine --machine ubuntu-22.04 --yes
          echo '```' >> $GITHUB_STEP_SUMMARY
          asv continuous --interleave-processes -a processes=2 --split --show-stderr '2a04e24d2dfc8e60a66e4369d970913cb2112d91' 'HEAD' |\
          sed -n -E '/(before.*after.*ratio)|(BENCHMARKS)/,$p' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Set Benchmark Result
        id: set_benchmark_result
        run: |-
          if grep "SOME BENCHMARKS HAVE CHANGED" $GITHUB_STEP_SUMMARY; then
            echo "::set-output name=BENCHMARK-RESULT::SOME BENCHMARKS CHANGED SIGNIFICANTLY PERFORMANCE REDUCED"
          else 
            echo "::set-output name=BENCHMARK-RESULT::SOME BENCHMARKS NOT CHANGED SIGNIFICANTLY"
          fi
      - name: Set status
        uses: "teamniteo/pull_request_status_action@v1.0.0"
        with:
          pr_number: ${{ github.event.number }}
          state: success
          context: 'Benchmarking Result'
          repository: deepakdinesh1123/Main
          description: ${{ steps.set_benchmark_result.outputs.BENCHMARK-RESULT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
