name: Benchmark

on:
  pull_request:
    types: [ labeled ]

jobs:
  Run_benchmarks:
    if: ${{ github.event.label.name == 'benchmark'}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout benchmarks
        uses: actions/checkout@v3
        with:
          repository: smithdc1/django-asv
          path: "."
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Cache Django
        uses: actions/cache@v3
        with:
          path: Django/*
          key: Django
      - name: Run Benchmarks
        shell: bash -l {0}
        run: |-
          asv machine --machine ubuntu-22.04 --yes
          echo '```' >> $GITHUB_STEP_SUMMARY
          asv continuous --interleave-processes -a processes=2 --split --show-stderr '2a04e24d2dfc8e60a66e4369d970913cb2112d91' 'HEAD' |\
          sed -n -E '/(before.*after.*ratio)|(BENCHMARKS)/,$p' >> out.txt
          cat out.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          if grep -q "PERFORMANCE DECREASED" out.txt;
          then
            exit 1
          fi
